### ISSUE TITLE
Missing config.py file in annotator/seg/init.py

### ISSUE THREAD

**Issue by mj-x** [Sonettoo/CRS-Diff#7]
Hello,
I encountered an issue，in the annotator/seg/init.py file at line 50, there is a reference to a config.py file (config = py2cfg("config.py")). However, this config.py file seems to be missing from the repository. Could you please provide this file or let me know where I can find it?
Thank you for your assistance.
![232](https://github.com/Sonettoo/CRS-Diff/assets/73381897/bfcade29-5cda-48fb-8caa-55436e79bb2e)

**Comment by Sonettoo** [comment]
You can find the relevant files and pre-trained weights here [GeoSeg](https://github.com/WangLibo1995/GeoSeg/blob/main/config/loveda/unetformer.py)

**Comment by mj-x** [comment]
您发给我的信件已经收到，非常感谢您的来信，我将尽快给您回复。This is an automatic reply, confirming that your e-mail was received.Thank you.

**Comment by mj-x** [comment]
您发给我的信件已经收到，非常感谢您的来信，我将尽快给您回复。This is an automatic reply, confirming that your e-mail was received.Thank you.
