### ISSUE TITLE
Questions about FID and IS

### ISSUE THREAD

**Issue by yiiizuo** [Sonettoo/CRS-Diff#8]
I am sorry to bother you.​

May I ask you if the real image of your paper FID is from remote sensing dataset or from ImageNet-1k? and where the weights of inception_v3 are from?

Also, what is the source of the inception_v3 weights used to compute IS in your paper?

**Comment by Sonettoo** [comment]
Hello, regarding the calculation of FID and IS is with reference to the implementation of [Txt2Img-MHN](https://github.com/YonghaoXu/Txt2Img-MHN?tab=readme-ov-file#gen), the weights of inception_v3 are obtained by training on the remote sensing images.

**Comment by yiiizuo** [comment]
Thank you for your reply.
Best wish!
