### ISSUE TITLE
在第一阶段模型训练的时候，您使用class free guidance 了吗

### ISSUE THREAD

**Issue by ZFU123456** [Sonettoo/CRS-Diff#9]
在第一阶段模型训练的时候，仅仅使用了RSICD数据集，您使用class free guidance 了吗？

**Comment by Sonettoo** [comment]
你好，使用了CFG的

**Comment by ZFU123456** [comment]
> 你好，使用了CFG的

![1721637829610](https://github.com/user-attachments/assets/fa144972-5065-4f73-8964-405998251248)
麻烦请问 我这样使用和您设置的CFG是一样的吗？

**Comment by ZFU123456** [comment]
> 抱歉，我可能理解错了。CFG在训练的时候只需要将文本按一定概率置为空就可以了，在推理的时候才会同时计算两种不同的噪声预测。

好的，感谢您的回复，然后还想问您，就是您设置的概率、训练的bachsize具体是多少啊，您方便把第一阶段的训练代码公开吗？

**Comment by Sonettoo** [comment]
训练的代码来自官方库的可用脚本[diffusers](https://github.com/huggingface/diffusers/tree/main/examples/text_to_image#installing-the-dependencies)。大致实验设置为：文本按照20%置为空，bs=1，train_steps=80k，learning_rate=1e-05
不好意思，这块代码没有整理:X，本地主要保留的是权重文件，如有需要可以分享

**Comment by ZFU123456** [comment]
> 训练的代码来自官方库的可用脚本[diffusers](https://github.com/huggingface/diffusers/tree/main/examples/text_to_image#installing-the-dependencies)。大致实验设置为：文本按照20%置为空，bs=1，train_steps=80k，learning_rate=1e-05 不好意思，这块代码没有整理:X，本地主要保留的是权重文件，如有需要可以分享

能分享吗，我的邮箱zhangfuhua@hnu.edu.cn，感谢

**Comment by Sonettoo** [comment]
已发送，也可以通过[云盘](https://drive.google.com/file/d/1o9khg2LC32olUYavSEmMPMjLg_cSzBIe/view)访问

**Comment by ZFU123456** [comment]
> 已发送，也可以通过[云盘](https://drive.google.com/file/d/1o9khg2LC32olUYavSEmMPMjLg_cSzBIe/view)访问

非常感谢！

**Comment by ZFU123456** [comment]
> 已发送，也可以通过[云盘](https://drive.google.com/file/d/1o9khg2LC32olUYavSEmMPMjLg_cSzBIe/view)访问

打扰了 您能否发一份diffusers格式的训练 好的模型，我转diffusers格式一直不成功
